[theme]
backgroundColor = "white"
primaryColor = "#7058a3"
font = "Roboto:https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap"

[server]
enableStaticServing = true